name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  flutter_screenutil: ^5.9.3
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter_map: ^7.0.2
  flutter_local_notifications: ^18.0.1
  # web_socket_channel: ^3.0.1
  websocket: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
